# Generated by Django 4.2.7 on 2023-11-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0002_alter_performance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='average_response_time',
            field=models.DateTimeField(),
        ),
    ]
