# Generated by Django 4.2.7 on 2023-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0004_alter_performance_average_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
