# Generated by Django 4.2.7 on 2023-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0005_alter_purchase_order_quality_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='fulfillment_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='quality_rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
